### ISSUE TITLE
MapConverter doesn't handle ParameterizedType as map values (Bugzilla Bug 498757)

### ISSUE THREAD

**Issue by mcculls** [eclipse-sisu/sisu.plexus#11]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 498757
Date: 2016-07-28 08:14:29 -0400
From: Guillaume BouÃ© &lt;<guillaume_boue@orange.fr>&gt;
To:   Stuart McCulloch &lt;<mcculls@gmail.com>&gt;
CC:   mcculls@gmail.com

Last updated: 2016-07-28 08:23:18 -0400

## Comment 2734754
Date: 2016-07-28 08:14:29 -0400
From: Guillaume BouÃ© &lt;<guillaume_boue@orange.fr>&gt;

When the MapConverter is used with the actual types containing a parameterized type as value, the method findElementType incorrectly returns Object.class as if it were a simple element type. The consequence is that a Map<String, Map<String, String>> (or a Map<String, List<String>>) cannot be converted properly: the values will all be null.

Reproducible test code configuring from an XML:

public class Main {
	
    private Map<String, Map<String, String>> map;

    public static void main(String[] args) throws Exception {
        new Main().test();
    }
	
    private void test() throws Exception {
        MapConverter converter = new MapConverter();
        ConverterLookup lookup = new DefaultConverterLookup();
        PlexusConfiguration configuration = new XmlPlexusConfiguration(
            Xpp3DomBuilder.build(new StringReader("<map><k><v>true</v></k></map>"))
        );
        Type[] typeArguments = ((ParameterizedType) getClass().getDeclaredField("map").getGenericType()).getActualTypeArguments();
        ExpressionEvaluator evaluator = new DefaultExpressionEvaluator();
        Object o = converter.fromConfiguration(lookup, configuration, Map.class, typeArguments, Main.class, null, evaluator, null);
        System.out.println(o); // prints "{k=null}", the "<v>true</v>" configuration was not converted
    }

}

A possible fix (tested with the above code) is to let findElementType return the raw type of the parameterized type:

    private static Class<?> findElementType( final Type[] typeArguments )
    {
        if ( null != typeArguments && typeArguments.length > 1 )
        {
            if ( typeArguments[1] instanceof Class<?> )
    	    {
                return (Class<?>) typeArguments[1];
    	    }
            if ( typeArguments[1] instanceof ParameterizedType )
            {
                return (Class<?>) ((ParameterizedType) typeArguments[1]).getRawType();
    	    }
        }
        return Object.class;
    }

The cast to (Class<?>) is safe since getRawType() always return a Class (http://stackoverflow.com/a/5767681/1743880).

## Comment 2734759
Date: 2016-07-28 08:23:18 -0400
From: Stuart McCulloch &lt;<mcculls@gmail.com>&gt;

Thanks for the report, I'll also fix CollectionConverter at the same time which has a similar method.

**Comment by kwin** [comment]
@mcculls Would it be possible to spin a release containing this fix?

**Comment by mcculls** [comment]
Hi @kwin - yes, I'm sorting out a milestone release which will contain this and other fixes

**Comment by mcculls** [comment]
Hi @kwin apologies for the delay, a new milestone release [0.9.0.M1](https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.plexus/0.9.0.M1/) is now available on Maven central
