### ISSUE TITLE
Require Java 7 (Bugzilla Bug 563526)

### ISSUE THREAD

**Issue by mcculls** [eclipse-sisu/sisu.plexus#15]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 563526
Date: 2020-05-24 14:59:33 -0400
From: Robert Scholte &lt;<eclipse@sourcegrounds.com>&gt;
To:   Project Inbox &lt;<sisu-inbox@eclipse.org>&gt;
CC:   m.th.mulders@xs4all.nl

Last updated: 2021-08-21 04:27:49 -0400

## Comment 3166933
Date: 2020-05-24 14:59:33 -0400
From: Robert Scholte &lt;<eclipse@sourcegrounds.com>&gt;

Related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=563525
This might be a good reason to require at least Java 7.

## Comment 3209163
Date: 2020-12-06 06:11:20 -0500
From: Maarten Mulders &lt;<m.th.mulders@xs4all.nl>&gt;

I have submitted a pull request through GitHub: https://github.com/eclipse/sisu.plexus/pull/3.

## Comment 3258445
Date: 2021-08-21 04:27:49 -0400
From: Robert Scholte &lt;<eclipse@sourcegrounds.com>&gt;

It looks like this one can be closed due to https://github.com/eclipse/sisu.plexus/commit/367eeb23ef90603985b25623e909a40a729ced69

**Comment by mthmulders** [comment]
Closed in [367eeb2](https://github.com/eclipse/sisu.plexus/commit/367eeb23ef90603985b25623e909a40a729ced69) indeed.
