### ISSUE TITLE
Support conversion to java.time types (requires Java 8)

### ISSUE THREAD

**Issue by kwin** [eclipse-sisu/sisu.plexus#23]
Conversion to [java.time](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) types (introduced with Java 8) should be supported similar to legacy `java.util.Date`.

Currently the code base is still compiled for Java 7, while this feature would require Java 8 at least.

**Comment by cstamas** [comment]
@mcculls ping on this please, any opinion pro or con?

**Comment by cstamas** [comment]
I'd say go for it, getting PR prepped fine, worst can happen it goes into next upcoming release :wink:
