### ISSUE TITLE
Throw exceptions when classes cannot be parsed

### ISSUE THREAD

**Issue by kwin** [eclipse-sisu/sisu.plexus#51]
As followup to https://github.com/eclipse/sisu.inject/issues/97 [PlexusAnnotatedBeanModule](https://github.com/eclipse/sisu.plexus/blob/5e8587eac8c4c079566dcd0ccb0d5dba40cb4169/org.eclipse.sisu.plexus/src/main/java/org/eclipse/sisu/plexus/PlexusAnnotatedBeanModule.java#L76) should leverage strict scanning.

**Comment by kwin** [comment]
@cstamas and @mcculls Do we need to expose strict scanning as configuration toggle in the `ContainerConfiguration` or is it fine to always enable that for Plexus (given that Maven is most probably/hopefully the only Plexus consumer these days)?

**Comment by kwin** [comment]
From Maven this is configured via

https://github.com/apache/maven/blob/16fc54da7f7ccc3d849d1f79b684506cdde00a09/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java#L680

and

https://github.com/eclipse/sisu.plexus/blob/5e8587eac8c4c079566dcd0ccb0d5dba40cb4169/org.eclipse.sisu.plexus/src/main/java/org/codehaus/plexus/DefaultPlexusContainer.java#L203

As the `ContainerConfiguration`'s classpath scanning is set to `SCANNING_INDEX` in https://github.com/apache/maven/blob/16fc54da7f7ccc3d849d1f79b684506cdde00a09/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java#L666 the `SpaceScanner` is constructed with `BeanScanning.INDEX` in https://github.com/eclipse/sisu.plexus/blob/5e8587eac8c4c079566dcd0ccb0d5dba40cb4169/org.eclipse.sisu.plexus/src/main/java/org/eclipse/sisu/plexus/PlexusAnnotatedBeanModule.java#L76

**Comment by kwin** [comment]
@cstamas proposed offline to not extend the legacy Plexus API (like `ContainerConfiguration`) but rather allow to create a `PlexusContainer` on top of an existing Sisu `SpaceModule`. That way Sisu API could be used in addition to Plexus API for configuration purposes.

Update: This does not work, as `PlexusContainer` manages several `SpaceModule`s (one per realm) which are dynamically created.

**Comment by kwin** [comment]
I tend to change the default to strict scanning for `PlexusAnnotatedBeanModule` without exposing any configuration option. Any concerns @cstamas or @mcculls?

**Comment by gnodet** [comment]
> I tend to change the default to strict scanning for `PlexusAnnotatedBeanModule` without exposing any configuration option. Any concerns @cstamas or @mcculls?

I'd rather go for a fully compatible change rather than a behaviour change without any config.
